spring:
  application:
     name: chat
  datasource:
    url: jdbc:mysql://localhost:3306/moz1mozi
    username: moz1mozi
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true    # ✅ SQL을 보기 좋게 포맷팅 (줄바꿈, 들여쓰기)
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-consumer-group
    template:
      default-topic: chat-messages

logging:
  level:
    root: info
